### ISSUE TITLE
Single Config File including Client Key

### ISSUE THREAD

**Issue by goforgold** [kota65535/github-openvpn-connect-action#47]
Hi Team,

My config file actually includes everything to connect to VPN and looks like below.

```
client
proto udp
explicit-exit-notify
remote x.x.x.x x
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_xxx name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
ignore-unknown-option block-outside-dns
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
<ca>
-----BEGIN CERTIFICATE-----
xxx
xxx
xxx
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
xxx
xxx
xxx
</cert>
<key>
-----BEGIN PRIVATE KEY-----
xxx
xxx
-----END PRIVATE KEY-----
</key>
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
xxx
xxx
xxx
-----END OpenVPN Static key V1-----
</tls-crypt>
```

Can you please suggest how to use this file? I have put this file in secrets.

**Comment by kota65535** [comment]
- Move the each content of `<key>` and  `<tls-crypt>` section to GitHub action secret
- Use them in `client_key` and `tls_auth_key` input parameter

```
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: client.ovpn
          client_key: ${{ secrets.OVPN_CLIENT_KEY }}
          tls_auth_key: ${{ secrets.OVPN_TLS_AUTH_KEY }}
```
