### ISSUE TITLE
auth-user-pass not working

### ISSUE THREAD

**Issue by Morriz** [kota65535/github-openvpn-connect-action#63]
Hi @kota65535, I am not sure `auth-user-pass` is working correctly. I have the following set:
```yaml
      with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.OVPN_CLIENT_KEY }}
          tls_auth_key: ${{ secrets.OVPN_TLS_AUTH_KEY }}
```
which leads to the following transformation in the `.ovpn` file:
```
auth-user-pass up.txt
key client.key
tls-auth ta.key 1
```
which does not take into account the password, as it is still asking for in on TTY. If I remove the `auth-user-pass` part and add `askpass pass.txt` with the password in it, then all is good.
